version: '3.8'

services:

  springboot:
    build: .
    container_name: "springboot_app"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bugdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: bugdb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql-data: